[BRE-101] Remove dept-devops from CODEOWNERS
bitwarden/key-connector pull request #149
Opened 2024-06-10 14:01 UTC by michalchecinski

Remove dept-devops from CODEOWNERS and add `dept-bre` for `.github/workflows/release.yml`.

https://bitwarden.atlassian.net/browse/BRE-101

2024-06-10 14:01 UTC, michalchecinski commented
Wait for the https://bitwarden.atlassian.net/servicedesk/customer/portal/5/TSD-648 to be done.

2024-10-16 17:58 UTC, vgrassia requested changes

2024-10-16 17:58 UTC, vgrassia commented on .github/CODEOWNERS
> +**/entrypoint.sh
```suggestion
## Docker files have joint ownership ##
**/Dockerfile @bitwarden/dept-bre @bitwarden/team-auth-dev
**/*.Dockerfile @bitwarden/dept-bre @bitwarden/team-auth-dev
**/.dockerignore @bitwarden/dept-bre @bitwarden/team-auth-dev
**/entrypoint.sh @bitwarden/dept-bre @bitwarden/team-auth-dev
```

2024-10-16 17:58 UTC, vgrassia commented on .github/CODEOWNERS
> +.github/workflows/release.yml
```suggestion
## BRE team owns these workflows ##
.github/workflows/publish.yml @bitwarden/dept-bre

## These workflows have joint ownership ##
.github/workflows/build.yml @bitwarden/dept-bre @bitwarden/team-auth-dev
.github/workflows/release.yml @bitwarden/dept-bre @bitwarden/team-auth-dev
.github/workflows/version-bump.yml @bitwarden/dept-bre @bitwarden/team-auth-dev
```

2024-10-17 14:11 UTC, vgrassia approved these changes

2024-10-22 15:35 UTC, vgrassia approved these changes

2024-10-23 19:20 UTC, trmartin4 approved these changes
As we've discussed, the Auth team has agreed to transition ownership of Key Connector to the KM team.

2024-10-23 19:20 UTC, merged

2024-10-24 09:56 UTC, quexten commented
Seems this didn't require KM review to be moved into KM ownership. Still, looks good to me. Thank you for assigning ownership!