Include actions to support Checkmarx and Sonar scanning workflow
bitwarden/key-connector pull request #162
Opened 2024-08-02 19:03 UTC by bwdil

## Type of change

- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Implement scanning workflow 

## Objective

[PM-7288](https://bitwarden.atlassian.net/browse/PM-7288) - Deploy scanning workflow organization wide

[PM-7288]: https://bitwarden.atlassian.net/browse/PM-7288

2024-08-02 19:07 UTC, withinfocus requested changes

2024-08-02 19:07 UTC, withinfocus commented on .github/workflows/scan.yml
> +        uses: github/codeql-action/upload-sarif@1b1aada464948af03b950897e5eb522f92603cc2 # v3.24.9
⚠️ There's a newer version of this.

2024-08-02 19:07 UTC, withinfocus commented on .github/workflows/scan.yml
> +  quality:
🎨 Follow what I did at https://github.com/bitwarden/server/blob/main/.github/workflows/scan.yml#L53 down. The caching doesn't work and can be removed, plus you should configure where tests are.

2024-08-02 19:40 UTC, bwdil commented on .github/workflows/scan.yml
> +  quality:
👀 please review again

2024-08-02 19:42 UTC, withinfocus approved these changes

2024-08-08 15:56 UTC, vgrassia approved these changes

2024-08-08 15:56 UTC, merged